

# Site settings
title: Dayal Chand Aichara
email: dc.aichara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/About Me" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: dcaichara07
github_username: dc-aichara
gitlab_username:  dc-aichara

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]

